apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployaks
  labels:
    app: autodeployaks
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718706030516
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployaks
  template:
    metadata:
      labels:
        app: autodeployaks
    spec:
      containers:
        - name: autodeployaks
          image: acrworkflow1718706030516.azurecr.io/image-workflow-1718706030516:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
