apiVersion: v1
kind: Service
metadata:
  name: autodeployaks
  namespace: namespace-workflow-1718706030516
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeployaks
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000